# https://source.android.com/docs/setup/build/building-pixel-kernels
[oriole-kernel]
src.git = "https://android.googlesource.com/kernel/common"
src.branch = "android-gs-raviole-6.1-android15-qpr2"
fetch.git = "https://android.googlesource.com/kernel/common"
[oriole-kernel14]
src.git = "https://android.googlesource.com/kernel/common"
src.branch = "android-gs-raviole-5.10-android14-qpr3"
fetch.git = "https://android.googlesource.com/kernel/common"
[enchilada-kernel]
src.git = "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git"
fetch.git = "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git"
[gta4xlwifi-kernel]
src.git = "https://github.com/LineageOS/android_kernel_samsung_gta4xl.git"
fetch.git = "https://github.com/LineageOS/android_kernel_samsung_gta4xl.git"
[vendor_gapps15]
src.git = "https://gitlab.com/MindTheGapps/vendor_gapps.git"
fetch.git = "https://gitlab.com/MindTheGapps/vendor_gapps.git"
src.branch = "vic"