# https://source.android.com/docs/setup/build/building-pixel-kernels
[akita-kernel]
src.git = "https://android.googlesource.com/kernel/common"
fetch.git = "https://android.googlesource.com/kernel/common"
src.branch = "android-gs-akita-6.1-android15-qpr2"
[oriole-kernel]
src.git = "https://android.googlesource.com/kernel/common"
src.branch = "android-gs-raviole-6.1-android15-qpr2"
fetch.git = "https://android.googlesource.com/kernel/common"
[enchilada-kernel]
src.git = "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git"
fetch.git = "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git"
[gta4xlwifi23-kernel]
src.git = "https://github.com/LineageOS/android_kernel_samsung_gta4xl.git"
src.branch = "lineage-23.0"
fetch.git = "https://github.com/LineageOS/android_kernel_samsung_gta4xl.git"
[gta4xlwifi-evobka-kernel]
src.git = "https://github.com/Evolution-X-Devices/kernel_samsung_gta4xl.git"
src.branch = "bka"
fetch.git = "https://github.com/Evolution-X-Devices/kernel_samsung_gta4xl.git"
[susfs414]
src.git = "https://gitlab.com/simonpunk/susfs4ksu.git"
src.branch = "kernel-4.14"
fetch.git = "https://gitlab.com/simonpunk/susfs4ksu.git"
[vendor_gapps15]
src.git = "https://gitlab.com/MindTheGapps/vendor_gapps.git"
src.branch = "vic"
# needed for blobs. fetchgit doesn't provide an option for git-lfs.
fetch.url = "https://gitlab.com/MindTheGapps/vendor_gapps/-/archive/$ver/vendor_gapps-$ver.tar.gz"
[vendor_gapps16]
src.git = "https://gitlab.com/MindTheGapps/vendor_gapps.git"
src.branch = "baklava"
# needed for blobs. fetchgit doesn't provide an option for git-lfs.
fetch.url = "https://gitlab.com/MindTheGapps/vendor_gapps/-/archive/$ver/vendor_gapps-$ver.tar.gz"