[oriole-kernel]
# https://source.android.com/docs/setup/build/building-pixel-kernels
src.git = "https://android.googlesource.com/kernel/common"
src.branch = "android-gs-raviole-6.1-android15-qpr2"
fetch.git = "https://android.googlesource.com/kernel/common"
[enchilada-kernel]
src.git = "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git"
fetch.git = "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git"
