# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  akita-kernel = {
    pname = "akita-kernel";
    version = "3c76c2d71bb32039037c6f5dc38b172fe4142bdb";
    src = fetchgit {
      url = "https://android.googlesource.com/kernel/common";
      rev = "3c76c2d71bb32039037c6f5dc38b172fe4142bdb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-QXHmdl7kdLspqLuVAcAw50AJ0rYKiLNyaRPqSpTnoWM=";
    };
    date = "2025-03-12";
  };
  enchilada-kernel = {
    pname = "enchilada-kernel";
    version = "b7798cdd4eb82e201b54dbb9b85662ee44e3b7cc";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git";
      rev = "b7798cdd4eb82e201b54dbb9b85662ee44e3b7cc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-FNeZqqIZRc9zpbPE7OXYG+UhofIr83S3ycRm/2nwEXc=";
    };
    date = "2026-01-06";
  };
  external_lxc = {
    pname = "external_lxc";
    version = "4e3a3630fff3dc04e0d4a761309f87f248e40b17";
    src = fetchgit {
      url = "https://github.com/Linux-on-droid/external_lxc.git";
      rev = "4e3a3630fff3dc04e0d4a761309f87f248e40b17";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lh/YEh1ubAW51GKFZiraQZqbGGkdT6zuSVunDRAaKbE=";
    };
    date = "2024-11-24";
  };
  grapheneos_kernel_pixel = {
    pname = "grapheneos_kernel_pixel";
    version = "aff4e27a786c017a00179036714ae5309681c784";
    src = fetchgit {
      url = "https://gitlab.com/grapheneos/kernel_pixel.git";
      rev = "aff4e27a786c017a00179036714ae5309681c784";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6E/DWOGXAfNfl2fr7JSszlFOSAetyTD11GtMd15b1II=";
    };
    date = "2026-02-28";
  };
  gta4xlwifi-evobka-kernel = {
    pname = "gta4xlwifi-evobka-kernel";
    version = "2c276961bbd7e6b8cad97219431182049bfc5e1c";
    src = fetchgit {
      url = "https://github.com/Evolution-X-Devices/kernel_samsung_gta4xl.git";
      rev = "2c276961bbd7e6b8cad97219431182049bfc5e1c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GSBGZEQM7kVS7Xr5A8yjDs822wbqZ3VXpD7+bNDIXUw=";
    };
    date = "2025-09-05";
  };
  gta4xlwifi23-kernel = {
    pname = "gta4xlwifi23-kernel";
    version = "352353d9ac0ad0617e07b624f883352eb29d570c";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_kernel_samsung_gta4xl.git";
      rev = "352353d9ac0ad0617e07b624f883352eb29d570c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mLQ2JitKF8ytdbY9L570g6tuK8Y7G8OUf3F0f5wKyGo=";
    };
    date = "2026-01-24";
  };
  libhybris = {
    pname = "libhybris";
    version = "419f3ff6736e01cb0e579f65a34c85cfa7de578b";
    src = fetchgit {
      url = "https://github.com/Linux-on-droid/libhybris.git";
      rev = "419f3ff6736e01cb0e579f65a34c85cfa7de578b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-h9QmJ/uZ2sHMGX3/UcxD+xe/myONacKwoBhmn0RK5sI=";
    };
    date = "2024-10-14";
  };
  lindroid_drm_loopback = {
    pname = "lindroid_drm_loopback";
    version = "9160b7c216bad31ef8d141a7d09f41d072999e8e";
    src = fetchgit {
      url = "https://github.com/Linux-on-droid/lindroid-drm-loopback.git";
      rev = "9160b7c216bad31ef8d141a7d09f41d072999e8e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-l3ReVmQYFVceLx587qf3SmFJAG2muwpliaWzoqU8qzM=";
    };
    date = "2026-02-26";
  };
  lineage_deskclock = {
    pname = "lineage_deskclock";
    version = "c482027bbad71cd48a8caf73b776a3d6d310206b";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_DeskClock.git";
      rev = "c482027bbad71cd48a8caf73b776a3d6d310206b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Fh0zfXctO1Rj/BaE+jI4bvlYcrEtuXEkKmhHYaTwfl8=";
    };
    date = "2026-02-07";
  };
  lineage_exactcalculator = {
    pname = "lineage_exactcalculator";
    version = "c9b0487d2c7b2fdfc58e01ed5c1c98f2e90246e0";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_ExactCalculator.git";
      rev = "c9b0487d2c7b2fdfc58e01ed5c1c98f2e90246e0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-o5dJ0n3gNYktMjjEsU/N0ovf1E30OlPb2GKpJoVUhSs=";
    };
    date = "2026-02-26";
  };
  lineage_latinime = {
    pname = "lineage_latinime";
    version = "7ef9404d0e9122e11329ac7f49536c0e2f6ca6fc";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_inputmethods_LatinIME.git";
      rev = "7ef9404d0e9122e11329ac7f49536c0e2f6ca6fc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JS/mANnyqel98o4F5/ECa6555lEGr8Y6+OOr5n2xB/s=";
    };
    date = "2026-02-01";
  };
  susfs414 = {
    pname = "susfs414";
    version = "77905b5a071e6f3669e3b1814cea30147c0801da";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "77905b5a071e6f3669e3b1814cea30147c0801da";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cbQNeNp+sbm/6PH1KWCH5ggGy9KbGbzX7qUkhmc+Tdc=";
    };
    date = "2025-02-23";
  };
  vendor_gapps15 = {
    pname = "vendor_gapps15";
    version = "af160b7fba89b2ea23aad432c7d0716e1639f0f9";
    src = fetchurl {
      url = "https://gitlab.com/MindTheGapps/vendor_gapps/-/archive/af160b7fba89b2ea23aad432c7d0716e1639f0f9/vendor_gapps-af160b7fba89b2ea23aad432c7d0716e1639f0f9.tar.gz";
      sha256 = "sha256-ZDPPagAlC/ECM4AdbYQOQX85sZq+JXzsDNLS3JCAud0=";
    };
    date = "2025-08-12";
  };
  vendor_gapps16 = {
    pname = "vendor_gapps16";
    version = "4d507e229e95d97d355e9ebaae64eb0d05236f92";
    src = fetchurl {
      url = "https://gitlab.com/MindTheGapps/vendor_gapps/-/archive/4d507e229e95d97d355e9ebaae64eb0d05236f92/vendor_gapps-4d507e229e95d97d355e9ebaae64eb0d05236f92.tar.gz";
      sha256 = "sha256-8nj3NbL/h5B2wU5wXvVNr4q6LGUogZaaQU2/hGxP4xk=";
    };
    date = "2026-02-08";
  };
  vendor_lindroid = {
    pname = "vendor_lindroid";
    version = "768bc42f2e794b7b4ff4e73c0adbb64b8235957d";
    src = fetchgit {
      url = "https://github.com/Linux-on-droid/vendor_lindroid.git";
      rev = "768bc42f2e794b7b4ff4e73c0adbb64b8235957d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TEDC8g8QsJdQJU9VPtMB9jV8Q6QolAD8RwPkUJTMBFc=";
    };
    date = "2026-02-27";
  };
}
