# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  axp_build = {
    pname = "axp_build";
    version = "adef6303e5cfce57f95822fdfe1db9d2fd5c87e1";
    src = fetchgit {
      url = "https://git.disroot.org/AXP.OS/build.git";
      rev = "adef6303e5cfce57f95822fdfe1db9d2fd5c87e1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Gy6/zJfpjjvgvfQ9WuJDZ9SEEfZt2wuxQ81Qg8OFQWY=";
    };
    date = "2026-05-25";
  };
  axp_kernel_patches = {
    pname = "axp_kernel_patches";
    version = "ea11c2374c76792ad88a06126df4570d30396229";
    src = fetchgit {
      url = "https://git.disroot.org/AXP.OS/kernel_patches.git";
      rev = "ea11c2374c76792ad88a06126df4570d30396229";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5FpKAFlEdsGuSACg1v2Ada+GlRCctpfLtKDYzZEbnzQ=";
    };
    date = "2026-07-30";
  };
  cola2261_device_dm3q = {
    pname = "cola2261_device_dm3q";
    version = "b2f80e645cd082399ecd4edb6ebba34305dc961c";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-cola2261/android_device_samsung_dm3q.git";
      rev = "b2f80e645cd082399ecd4edb6ebba34305dc961c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/2qS6ljCrpQ7ai8H/eqK7RQLvVZLOloh4uVLxVoS7ak=";
    };
    date = "2026-07-20";
  };
  cola2261_device_sm8550_common = {
    pname = "cola2261_device_sm8550_common";
    version = "c479ea89db5716bfce032a8afe0d63f85f8c3c1f";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-cola2261/android_device_samsung_sm8550-common.git";
      rev = "c479ea89db5716bfce032a8afe0d63f85f8c3c1f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rJJemYSsqtIs4ZJIqck0EJYY58bGwd/TIF2p9AovT94=";
    };
    date = "2026-07-20";
  };
  cola2261_hardware_samsung = {
    pname = "cola2261_hardware_samsung";
    version = "4f3afca5e2af0b447b3efd3973ecb69c63a5f918";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-cola2261/android_hardware_samsung.git";
      rev = "4f3afca5e2af0b447b3efd3973ecb69c63a5f918";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-uQbbwazvQ0zs7JB1ZyzLyUMONzYlJXHWZE7gVvMhzjQ=";
    };
    date = "2025-12-08";
  };
  cola2261_kernel_sm8550 = {
    pname = "cola2261_kernel_sm8550";
    version = "c10438709d017451a5845217252b7cf3e97e0177";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-cola2261/android_kernel_samsung_sm8550.git";
      rev = "c10438709d017451a5845217252b7cf3e97e0177";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/aMZ5PAkEA8enrJ+WxY/a1J2GsHOJ0NnLtiD/+pXQ7A=";
    };
    date = "2026-07-23";
  };
  cola2261_kernel_sm8550_modules = {
    pname = "cola2261_kernel_sm8550_modules";
    version = "2f3d47292a970a6e2a25cad8dab6daa4c019df0f";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-cola2261/android_kernel_samsung_sm8550-modules.git";
      rev = "2f3d47292a970a6e2a25cad8dab6daa4c019df0f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8DnvLYVdpGxfOQdEp6Li6p4zax+dzKqkKInGnBr7zTw=";
    };
    date = "2026-07-21";
  };
  cola2261_vendor_dm3q = {
    pname = "cola2261_vendor_dm3q";
    version = "2648d2614ef45238a1028e71fa9e0d42ad57b515";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-cola2261/proprietary_vendor_samsung_dm3q.git";
      rev = "2648d2614ef45238a1028e71fa9e0d42ad57b515";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-TevXah7/2zGQ9rZF1IDIu/gFptmSuS9r9K5W32kPaaA=";
    };
    date = "2026-07-02";
  };
  cola2261_vendor_sm8550_common = {
    pname = "cola2261_vendor_sm8550_common";
    version = "5647f7d15702e89c5cac1edfa6991a59093c701c";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-cola2261/proprietary_vendor_samsung_sm8550-common.git";
      rev = "5647f7d15702e89c5cac1edfa6991a59093c701c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LzkVqNmc2X7VFGcxe398Qyy2FNtAVrynaqe6e3RUvPY=";
    };
    date = "2026-07-02";
  };
  derpfest16_device_oneplus_enchilada = {
    pname = "derpfest16_device_oneplus_enchilada";
    version = "0ffb6826a8e39b6208d03e430320bf1b782185f6";
    src = fetchgit {
      url = "https://github.com/ppanzenboeck/device_oneplus_enchilada.git";
      rev = "0ffb6826a8e39b6208d03e430320bf1b782185f6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wG8YT+g2o1Rb0bDrjJ1D9+gDTa6AsKmMZLhaE6iUseg=";
    };
    date = "2026-04-15";
  };
  derpfest16_device_oneplus_sdm845_common = {
    pname = "derpfest16_device_oneplus_sdm845_common";
    version = "279a14fbb48544071f2352b84eab511f377c1ea8";
    src = fetchgit {
      url = "https://github.com/ppanzenboeck/device_oneplus_sdm845-common.git";
      rev = "279a14fbb48544071f2352b84eab511f377c1ea8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-uMcuA/xBEijfxSncLWEISlNl6dVooHnkvINmln4HqYU=";
    };
    date = "2026-03-17";
  };
  derpfest16_hardware_oneplus = {
    pname = "derpfest16_hardware_oneplus";
    version = "58032612ed86f943ac0fe927a833156d26fcbdf8";
    src = fetchgit {
      url = "https://github.com/ppanzenboeck/hardware_oneplus.git";
      rev = "58032612ed86f943ac0fe927a833156d26fcbdf8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2AaNAbTnNYBXq5tug3of0RZZngm8gTjFyhHMgjodT4Y=";
    };
    date = "2026-05-10";
  };
  derpfest16_kernel_oneplus_sdm845 = {
    pname = "derpfest16_kernel_oneplus_sdm845";
    version = "9b322418d63762b3bec0c824a656227a6607aa9d";
    src = fetchgit {
      url = "https://github.com/ppanzenboeck/kernel_oneplus_sdm845.git";
      rev = "9b322418d63762b3bec0c824a656227a6607aa9d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3w7YBmhKSNsQFDrYNUtd/Uv6P5MPY6u/v4oS6RI2lNY=";
    };
    date = "2026-03-17";
  };
  derpfest_launcher3 = {
    pname = "derpfest_launcher3";
    version = "b7ff1591907a46380021dfd474124466a085fdb1";
    src = fetchgit {
      url = "https://github.com/DerpFest-AOSP/android_packages_apps_DerpLauncher.git";
      rev = "b7ff1591907a46380021dfd474124466a085fdb1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-h5i8cPZNpXtKccQPpgyj4ZxO869Nke82Y4/Uup3PrJY=";
    };
    date = "2026-06-18";
  };
  evox_launcher3 = {
    pname = "evox_launcher3";
    version = "6f469e925d61c856360ee067cd29d5e136457151";
    src = fetchgit {
      url = "https://github.com/Evolution-X/packages_apps_Launcher3.git";
      rev = "6f469e925d61c856360ee067cd29d5e136457151";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/ol/RbOUByAWOZ/II+4D6cFOloEUd96jg3bdT0dEr7o=";
    };
    date = "2026-02-03";
  };
  external_lxc = {
    pname = "external_lxc";
    version = "4e3a3630fff3dc04e0d4a761309f87f248e40b17";
    src = fetchgit {
      url = "https://github.com/Linux-on-droid/external_lxc.git";
      rev = "4e3a3630fff3dc04e0d4a761309f87f248e40b17";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lh/YEh1ubAW51GKFZiraQZqbGGkdT6zuSVunDRAaKbE=";
    };
    date = "2024-11-24";
  };
  google_gallery = {
    pname = "google_gallery";
    version = "8ebb28aa67c8d538b7d6c19c7949e25f7ae5f232";
    src = fetchgit {
      url = "https://github.com/google-ai-edge/gallery.git";
      rev = "8ebb28aa67c8d538b7d6c19c7949e25f7ae5f232";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NTk1rX0PDGfdHCegpUxey+epZYYFnew3D2aSxMSawfM=";
    };
    date = "2026-07-31";
  };
  grapheneos_appstore = {
    pname = "grapheneos_appstore";
    version = "8a98fbd4fa58f5d649cf3396d3bbbeaa96f9e65d";
    src = fetchgit {
      url = "https://github.com/GrapheneOS/AppStore.git";
      rev = "8a98fbd4fa58f5d649cf3396d3bbbeaa96f9e65d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-RDFogeSHPh8+AAsS81Vq5kZh/5PJLIs3tDlHVlSvaEQ=";
    };
    date = "2026-07-08";
  };
  grapheneos_camera = {
    pname = "grapheneos_camera";
    version = "0a88f7330761d3156389d556e9b24e9e9cd2629e";
    src = fetchgit {
      url = "https://github.com/GrapheneOS/Camera.git";
      rev = "0a88f7330761d3156389d556e9b24e9e9cd2629e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-m8eNxF80v2a9ciG+1o+wcjIOuFOdx0tfeGUKrLrkYGc=";
    };
    date = "2026-08-01";
  };
  grapheneos_info = {
    pname = "grapheneos_info";
    version = "ea28e0b6bba4df01544f9eaf57193f46eb72091a";
    src = fetchgit {
      url = "https://github.com/GrapheneOS/Info.git";
      rev = "ea28e0b6bba4df01544f9eaf57193f46eb72091a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sdx5NQK/kp10yRVsk8qhOP3TrIegc2VihO/kPQric4Y=";
    };
    date = "2026-07-22";
  };
  grapheneos_pdfviewer = {
    pname = "grapheneos_pdfviewer";
    version = "a6618aa3036c0b73475f3b09485173a2b598f432";
    src = fetchgit {
      url = "https://github.com/GrapheneOS/PdfViewer.git";
      rev = "a6618aa3036c0b73475f3b09485173a2b598f432";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XlPaWNnBrxbT9X2qEiJ0mDuBPUowfsUnvJ8E7Ruji7E=";
    };
    date = "2026-07-30";
  };
  grapheneos_vanadium = {
    pname = "grapheneos_vanadium";
    version = "670dd99e7ba5b79be895d4144209ea0bea0ec773";
    src = fetchgit {
      url = "https://gitlab.com/grapheneos/platform_external_vanadium.git";
      rev = "670dd99e7ba5b79be895d4144209ea0bea0ec773";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sJ99VbcWOBc2PQND0QDwY47IrfZCBY7fOeUqeNvuMl0=";
    };
    date = "2026-06-17";
  };
  gta4xlwifi-evobka-kernel = {
    pname = "gta4xlwifi-evobka-kernel";
    version = "2c276961bbd7e6b8cad97219431182049bfc5e1c";
    src = fetchgit {
      url = "https://github.com/Evolution-X-Devices/kernel_samsung_gta4xl.git";
      rev = "2c276961bbd7e6b8cad97219431182049bfc5e1c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GSBGZEQM7kVS7Xr5A8yjDs822wbqZ3VXpD7+bNDIXUw=";
    };
    date = "2025-09-05";
  };
  libhybris = {
    pname = "libhybris";
    version = "29e0fa6da0166261f6b9437582fe2d56bab8530c";
    src = fetchgit {
      url = "https://github.com/Linux-on-droid/libhybris.git";
      rev = "29e0fa6da0166261f6b9437582fe2d56bab8530c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-5Ji9R1M0PKNWb8mQyMESQAI2qRli2GMIIMMVDsjZ7NE=";
    };
    date = "2026-05-29";
  };
  lindroid_drm_loopback = {
    pname = "lindroid_drm_loopback";
    version = "d3b85f3251beae4bc8481538f37d13b7f30abde0";
    src = fetchgit {
      url = "https://github.com/Linux-on-droid/lindroid-drm-loopback.git";
      rev = "d3b85f3251beae4bc8481538f37d13b7f30abde0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mEJ3LY4lNoWLaFz9ANfRAzZpOaTJnkbZwBR0Oe1pyyg=";
    };
    date = "2026-06-24";
  };
  lineage_deskclock = {
    pname = "lineage_deskclock";
    version = "86b8c631886ca7981bacc3097fe784207de40b7f";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_DeskClock.git";
      rev = "86b8c631886ca7981bacc3097fe784207de40b7f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yODp4Sr1PkdbLXCy/wSivgngh1d3WgUMsnPvpvRu6o4=";
    };
    date = "2026-07-15";
  };
  lineage_device_mainline_common = {
    pname = "lineage_device_mainline_common";
    version = "7f452be29c56afa8654432119edee52eb199a2c5";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_device_mainline_common.git";
      rev = "7f452be29c56afa8654432119edee52eb199a2c5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-wq9xjbsjy+yTsKP6AAy3agY6tvuJtEnm49Sf0C/Vjt0=";
    };
    date = "2026-07-14";
  };
  lineage_device_virt_common = {
    pname = "lineage_device_virt_common";
    version = "778a68f9268858e419e69cc88ac07b5553977fe9";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_device_virt_virt-common.git";
      rev = "778a68f9268858e419e69cc88ac07b5553977fe9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2SY7uyrTyf0MkP+0/MOU1iVyzElJrjyPRjFLKTGP5UQ=";
    };
    date = "2026-06-21";
  };
  lineage_device_virtio_arm64 = {
    pname = "lineage_device_virtio_arm64";
    version = "3346a2fb77da6c8a2728cca8313530ba74de3798";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_device_virt_virtio_arm64.git";
      rev = "3346a2fb77da6c8a2728cca8313530ba74de3798";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GxorbnqWIDTWbWiI3lyAv3byhR9/1PUVvgZWL1XAO3A=";
    };
    date = "2025-12-11";
  };
  lineage_device_virtio_arm64only = {
    pname = "lineage_device_virtio_arm64only";
    version = "05609653c67fe93de3a7f0e115a1680355c9a8e5";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_device_virt_virtio_arm64only.git";
      rev = "05609653c67fe93de3a7f0e115a1680355c9a8e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fZCK7Xq5nevpzSAp+cb16wTxwGZzgF3EfkX9ARktSF8=";
    };
    date = "2025-11-11";
  };
  lineage_device_virtio_common = {
    pname = "lineage_device_virtio_common";
    version = "74ef24f0726a7f6a3a05a1527f574ba6a47daad9";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_device_virt_virtio-common.git";
      rev = "74ef24f0726a7f6a3a05a1527f574ba6a47daad9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KH3u9nzofqcRVE448J4xWSOREZoOFeTAIwQTHwDsX5s=";
    };
    date = "2026-02-01";
  };
  lineage_exactcalculator = {
    pname = "lineage_exactcalculator";
    version = "af4a9397439223d0f572823d66c7985619da3e45";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_ExactCalculator.git";
      rev = "af4a9397439223d0f572823d66c7985619da3e45";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-8bBMsfspH0CxhdKaU+lijehwBUaPK0Zh+u5+bkh6BZA=";
    };
    date = "2026-06-08";
  };
  lineage_external_drm_hwcomposer_upstream = {
    pname = "lineage_external_drm_hwcomposer_upstream";
    version = "8976786556df09c42b4ad41dd93969c6792f324d";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_external_drm_hwcomposer-upstream.git";
      rev = "8976786556df09c42b4ad41dd93969c6792f324d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-e5FO88tXedYuefhGqZfLjVFHLcNKfJXM/98/wUAnQfg=";
    };
    date = "2026-01-19";
  };
  lineage_external_libdisplay_info_upstream = {
    pname = "lineage_external_libdisplay_info_upstream";
    version = "d24cede4ffdeb8a130d5923a04a315aa02a1de79";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_external_libdisplay-info-upstream.git";
      rev = "d24cede4ffdeb8a130d5923a04a315aa02a1de79";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VXikD7CkMIGjGrSJOhveWtGbyM7Z7xf7VILH1FLXshY=";
    };
    date = "2026-01-19";
  };
  lineage_external_linux_firmware_mainline = {
    pname = "lineage_external_linux_firmware_mainline";
    version = "ef88d24dfc10e30826789b82fca417d6f913ee2a";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_external_linux-firmware-mainline.git";
      rev = "ef88d24dfc10e30826789b82fca417d6f913ee2a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZpL3VF0nmER/tbNPC9KgGpZ37HOnTU7YeP7sdNcrC8E=";
    };
    date = "2026-06-05";
  };
  lineage_external_mesa = {
    pname = "lineage_external_mesa";
    version = "592114e9e6ba5520db69232a8f7e685ab6b70fd8";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_external_mesa.git";
      rev = "592114e9e6ba5520db69232a8f7e685ab6b70fd8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DLmzpo5IWKzG1HkDGRa8WX8vHKHrD8jzIqTvGZyCdZA=";
    };
    date = "2026-06-30";
  };
  lineage_external_minigbm_upstream = {
    pname = "lineage_external_minigbm_upstream";
    version = "51b97430ef97474b386bc958d67e5171a86d0d76";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_external_minigbm-upstream.git";
      rev = "51b97430ef97474b386bc958d67e5171a86d0d76";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/IbZg4nGYLyD4XVU1EOKNGiMaOu5aVJPSWMZvMVbngo=";
    };
    date = "2026-06-23";
  };
  lineage_gallery2 = {
    pname = "lineage_gallery2";
    version = "73803da5c066e0d6f67319d28087c965234b7850";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_Gallery2.git";
      rev = "73803da5c066e0d6f67319d28087c965234b7850";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-oOpYWQg27G8SJKtB8qujaVQLObw4ZMlTnE4khF/6J1w=";
    };
    date = "2026-05-17";
  };
  lineage_glimpse = {
    pname = "lineage_glimpse";
    version = "160c5b63b817ad28b1b91b34799339d1b9fa1b1b";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_Glimpse.git";
      rev = "160c5b63b817ad28b1b91b34799339d1b9fa1b1b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v70tiIvrPFwjdieWApwOq1kFUIQwpnc7lRBgg/3CuSI=";
    };
    date = "2026-08-01";
  };
  lineage_hardware_mainline_common = {
    pname = "lineage_hardware_mainline_common";
    version = "3ce6782c36ee220b0672f0ecf976395afaf98486";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_hardware_mainline_common.git";
      rev = "3ce6782c36ee220b0672f0ecf976395afaf98486";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-21oelnRDEHtaMl+KxF6qwoJVX7acZrZf7fvtvQK26xs=";
    };
    date = "2026-04-28";
  };
  lineage_kernel_mainline_configs = {
    pname = "lineage_kernel_mainline_configs";
    version = "77b6adebc72ebe9c4646b88346570c9c057a62d7";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_kernel_mainline_configs.git";
      rev = "77b6adebc72ebe9c4646b88346570c9c057a62d7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iNO4/hldAECLimBkP4gKb3CvO2GZe4mfo8SuxI0U49U=";
    };
    date = "2026-07-27";
  };
  lineage_kernel_virt_virtio = {
    pname = "lineage_kernel_virt_virtio";
    version = "f5d9986a0f480fc0887804c751b3155c0c4da06a";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_kernel_virt_virtio.git";
      rev = "f5d9986a0f480fc0887804c751b3155c0c4da06a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZQowVhIcNZNCoIDt3P2kvgPAIshYsUZfH2GO+McFod0=";
    };
    date = "2025-12-31";
  };
  lineage_latinime = {
    pname = "lineage_latinime";
    version = "a1c8d3bd7f92f1bf0ba9a98690a56934841d6a18";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_inputmethods_LatinIME.git";
      rev = "a1c8d3bd7f92f1bf0ba9a98690a56934841d6a18";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7J6kua/iS4uvwuNUZPB061tvRVyFaoq2mbduHcINQxM=";
    };
    date = "2026-08-01";
  };
  lineage_launcher3 = {
    pname = "lineage_launcher3";
    version = "e3f4473fa3713d636a7062af9ffddfba07eff20f";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_Launcher3.git";
      rev = "e3f4473fa3713d636a7062af9ffddfba07eff20f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-csDXBaKESxnDAXG8+REgHkW+SAxQm8c4lUffiiuhKw4=";
    };
    date = "2026-08-01";
  };
  lineage_launcher3_wip = {
    pname = "lineage_launcher3_wip";
    version = "e3f4473fa3713d636a7062af9ffddfba07eff20f";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_Launcher3.git";
      rev = "e3f4473fa3713d636a7062af9ffddfba07eff20f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-csDXBaKESxnDAXG8+REgHkW+SAxQm8c4lUffiiuhKw4=";
    };
    date = "2026-08-01";
  };
  lineage_prebuilts_bootmgr = {
    pname = "lineage_prebuilts_bootmgr";
    version = "811ba971e891b1f3e7412dfcaac633af5517892f";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_prebuilts_bootmgr.git";
      rev = "811ba971e891b1f3e7412dfcaac633af5517892f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zXwaM3Vf9L/xm8w/kpXKJpQBp5WDU6cY3arzGXnSj2g=";
    };
    date = "2026-02-18";
  };
  lineage_recorder = {
    pname = "lineage_recorder";
    version = "1c93a84d0c32a99cd56e206d21d3d72094215c9e";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_packages_apps_Recorder.git";
      rev = "1c93a84d0c32a99cd56e206d21d3d72094215c9e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-G4APU06XDp2YvXoJABvwnx8jm25GIm350SXzPb/vKMA=";
    };
    date = "2026-06-15";
  };
  morphe_apktool = {
    pname = "morphe_apktool";
    version = "04517bc7c687a6cfdcd813abb02e3134487baa95";
    src = fetchgit {
      url = "https://github.com/MorpheApp/Apktool.git";
      rev = "04517bc7c687a6cfdcd813abb02e3134487baa95";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dgrjGXGJ86RDjBFB//1rOy7m1uxh3j3ZuXHRgRmLneQ=";
    };
    date = "2025-12-07";
  };
  morphe_multidexlib2 = {
    pname = "morphe_multidexlib2";
    version = "41cccc644cf1804362f7aa2fae96a6ffe67ffd22";
    src = fetchgit {
      url = "https://github.com/MorpheApp/multidexlib2.git";
      rev = "41cccc644cf1804362f7aa2fae96a6ffe67ffd22";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NBubLnNjkZbGFlSCkwbTdvjDeYdRn4xJBJUNCCs/ccU=";
    };
    date = "2026-03-13";
  };
  sm8550_tab_device_gts9wifi = {
    pname = "sm8550_tab_device_gts9wifi";
    version = "9acd725f3dc46d5e88d913bfba04e5bb8a056759";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-tab/android_device_samsung_gts9wifi.git";
      rev = "9acd725f3dc46d5e88d913bfba04e5bb8a056759";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AllU65KOUfwBsE95kxwqpC+EkHSyJyYfFegteIetwKY=";
    };
    date = "2026-05-15";
  };
  sm8550_tab_device_sm8550_common = {
    pname = "sm8550_tab_device_sm8550_common";
    version = "f8679e52f10e985bd2ceb9228760d8437634fcb7";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-tab/android_device_samsung_sm8550-common.git";
      rev = "f8679e52f10e985bd2ceb9228760d8437634fcb7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UstWyznDKIdrhxnBTSMt6ir4PVHoS3msmqs03znzpqs=";
    };
    date = "2026-05-15";
  };
  sm8550_tab_hardware_samsung = {
    pname = "sm8550_tab_hardware_samsung";
    version = "d893261eda11a0c7166d5af8cba639a9c081e7e1";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-tab/android_hardware_samsung.git";
      rev = "d893261eda11a0c7166d5af8cba639a9c081e7e1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-50lnCmnsGJXtfll7vfzQ2d8Il6/S0vvktXPXbs0uh30=";
    };
    date = "2026-05-16";
  };
  sm8550_tab_kernel_sm8550 = {
    pname = "sm8550_tab_kernel_sm8550";
    version = "f52247296f8b456216fc908ac95e30c279fd0e7c";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-tab/android_kernel_samsung_sm8550.git";
      rev = "f52247296f8b456216fc908ac95e30c279fd0e7c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1fbZR3Kf9iRMiavM0o5Ay595dUa50+1Urax9jodOXi4=";
    };
    date = "2026-05-15";
  };
  sm8550_tab_kernel_sm8550_modules = {
    pname = "sm8550_tab_kernel_sm8550_modules";
    version = "4dc7560de3e554b5a1bff6d751c247dd3414acd1";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-tab/android_kernel_samsung_sm8550-modules.git";
      rev = "4dc7560de3e554b5a1bff6d751c247dd3414acd1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DCkn/hHTgQgUF9MFTup8g+hKmZE8Z08htJUa1ee9kbA=";
    };
    date = "2026-05-16";
  };
  sm8550_tab_vendor_gts9wifi = {
    pname = "sm8550_tab_vendor_gts9wifi";
    version = "bd0882d36594e1dbd772e14d9cdeb6c655718385";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-tab/android_vendor_samsung_gts9wifi.git";
      rev = "bd0882d36594e1dbd772e14d9cdeb6c655718385";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-b2pD44lvDgZkeNpzJI6GBal0GyAfHneBjVAFFWLtZ4Q=";
    };
    date = "2025-10-28";
  };
  sm8550_tab_vendor_sm8550_common = {
    pname = "sm8550_tab_vendor_sm8550_common";
    version = "baf2fdd19d0dae4e422da8002cf61143f1f1c325";
    src = fetchgit {
      url = "https://github.com/samsung-sm8550-tab/android_vendor_samsung_sm8550-common.git";
      rev = "baf2fdd19d0dae4e422da8002cf61143f1f1c325";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xLNO4qmP48ct7huA7xja15r5XtQNfX267WWXpXTkTVI=";
    };
    date = "2025-10-28";
  };
  susfs414 = {
    pname = "susfs414";
    version = "77905b5a071e6f3669e3b1814cea30147c0801da";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "77905b5a071e6f3669e3b1814cea30147c0801da";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cbQNeNp+sbm/6PH1KWCH5ggGy9KbGbzX7qUkhmc+Tdc=";
    };
    date = "2025-02-23";
  };
  susfs419 = {
    pname = "susfs419";
    version = "001e69919c6271f690fd00b17e4c721c9e599152";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "001e69919c6271f690fd00b17e4c721c9e599152";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-j4OIvgOE64nm67NyGsEnSRNygVVZaF5uhMx8ju+p6fQ=";
    };
    date = "2025-02-23";
  };
  termux_app = {
    pname = "termux_app";
    version = "3df69d1da197dd9bd71a3bafd902dffd720576b4";
    src = fetchgit {
      url = "https://github.com/termux/termux-app.git";
      rev = "3df69d1da197dd9bd71a3bafd902dffd720576b4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-acSPHrz6rkc6jigNF1XnsqADqVvgOju6VNiYcwykCb4=";
    };
    date = "2026-07-15";
  };
  termux_x11 = {
    pname = "termux_x11";
    version = "cd2945932d0d81b17285da86f1565a364a1a709e";
    src = fetchgit {
      url = "https://github.com/termux/termux-x11.git";
      rev = "cd2945932d0d81b17285da86f1565a364a1a709e";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0XHdtcntkO4RVYIHQz92YPSiYzl2feKPTbnvmPMOGxw=";
    };
    date = "2026-08-02";
  };
  vendor_gapps15 = {
    pname = "vendor_gapps15";
    version = "af160b7fba89b2ea23aad432c7d0716e1639f0f9";
    src = fetchurl {
      url = "https://gitlab.com/MindTheGapps/vendor_gapps/-/archive/af160b7fba89b2ea23aad432c7d0716e1639f0f9/vendor_gapps-af160b7fba89b2ea23aad432c7d0716e1639f0f9.tar.gz";
      sha256 = "sha256-ZDPPagAlC/ECM4AdbYQOQX85sZq+JXzsDNLS3JCAud0=";
    };
    date = "2025-08-12";
  };
  vendor_gapps16 = {
    pname = "vendor_gapps16";
    version = "f8cdcffc2fb9181b8cc5a9b02d4b5908b64e5cdd";
    src = fetchurl {
      url = "https://gitlab.com/MindTheGapps/vendor_gapps/-/archive/f8cdcffc2fb9181b8cc5a9b02d4b5908b64e5cdd/vendor_gapps-f8cdcffc2fb9181b8cc5a9b02d4b5908b64e5cdd.tar.gz";
      sha256 = "sha256-g/kJGdrl59hZ8ojSD7eH/9nYzhf5u3VXjqUtrnPA7MU=";
    };
    date = "2026-06-12";
  };
  vendor_lindroid = {
    pname = "vendor_lindroid";
    version = "eadbb70f13209133d96a5355464388db8c6578de";
    src = fetchgit {
      url = "https://github.com/Linux-on-droid/vendor_lindroid.git";
      rev = "eadbb70f13209133d96a5355464388db8c6578de";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hCzokst8gNIODntQgVIBbB/X7R9Rud71BdEIlyOEk3k=";
    };
    date = "2026-07-02";
  };
}
