# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  enchilada-kernel = {
    pname = "enchilada-kernel";
    version = "eabce74f5a9cb3111570c2e3c3a99ae0046ae580";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_kernel_oneplus_sdm845.git";
      rev = "eabce74f5a9cb3111570c2e3c3a99ae0046ae580";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-jeb1Fpfm0uGncpYPLdI/w/8pj8wjFJMOZn885DfnKqA=";
    };
    date = "2025-07-11";
  };
  gta4xlwifi-evobka-kernel = {
    pname = "gta4xlwifi-evobka-kernel";
    version = "df7598e4aabe7efc26c0a37871b8ee4d72dc8acb";
    src = fetchgit {
      url = "https://github.com/Evolution-X-Devices/kernel_samsung_gta4xl.git";
      rev = "df7598e4aabe7efc26c0a37871b8ee4d72dc8acb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-P41831dfS5dJqB595/bzpjXgHcn3lX7QY1CoRFt+oLw=";
    };
    date = "2025-03-22";
  };
  gta4xlwifi-kernel = {
    pname = "gta4xlwifi-kernel";
    version = "df7598e4aabe7efc26c0a37871b8ee4d72dc8acb";
    src = fetchgit {
      url = "https://github.com/LineageOS/android_kernel_samsung_gta4xl.git";
      rev = "df7598e4aabe7efc26c0a37871b8ee4d72dc8acb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-P41831dfS5dJqB595/bzpjXgHcn3lX7QY1CoRFt+oLw=";
    };
    date = "2025-03-22";
  };
  oriole-kernel = {
    pname = "oriole-kernel";
    version = "3c76c2d71bb32039037c6f5dc38b172fe4142bdb";
    src = fetchgit {
      url = "https://android.googlesource.com/kernel/common";
      rev = "3c76c2d71bb32039037c6f5dc38b172fe4142bdb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-QXHmdl7kdLspqLuVAcAw50AJ0rYKiLNyaRPqSpTnoWM=";
    };
    date = "2025-03-12";
  };
  susfs414 = {
    pname = "susfs414";
    version = "77905b5a071e6f3669e3b1814cea30147c0801da";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "77905b5a071e6f3669e3b1814cea30147c0801da";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cbQNeNp+sbm/6PH1KWCH5ggGy9KbGbzX7qUkhmc+Tdc=";
    };
    date = "2025-02-23";
  };
  vendor_gapps15 = {
    pname = "vendor_gapps15";
    version = "af160b7fba89b2ea23aad432c7d0716e1639f0f9";
    src = fetchurl {
      url = "https://gitlab.com/MindTheGapps/vendor_gapps/-/archive/af160b7fba89b2ea23aad432c7d0716e1639f0f9/vendor_gapps-af160b7fba89b2ea23aad432c7d0716e1639f0f9.tar.gz";
      sha256 = "sha256-ZDPPagAlC/ECM4AdbYQOQX85sZq+JXzsDNLS3JCAud0=";
    };
    date = "2025-08-12";
  };
  vendor_gapps16 = {
    pname = "vendor_gapps16";
    version = "32ba6a5cab7c2435d2553f0746f29ef399aae0e7";
    src = fetchurl {
      url = "https://gitlab.com/MindTheGapps/vendor_gapps/-/archive/32ba6a5cab7c2435d2553f0746f29ef399aae0e7/vendor_gapps-32ba6a5cab7c2435d2553f0746f29ef399aae0e7.tar.gz";
      sha256 = "sha256-KlX5mo24nmoYVuRKBEgiUalziJu6GLt9dQELQrKX3oo=";
    };
    date = "2025-08-11";
  };
}
