name: "Build and populate cache"
on:
  schedule:
    - cron: '44 */3 * * *'
  pull_request:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
        cachixName:
          - mio-repo
        nixPath:
          - nixpkgs=https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-unstable.tar.gz
    runs-on: "${{ matrix.os }}"
    steps:
    - name: Maximize build space
      if: runner.os == 'Linux'
      uses: mio-19/maximize-build-space@patch-1
      with:
        root-reserve-mb: 512
        swap-size-mb: 12000
        overprovision-lvm: 'true'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        build-mount-path: /nix
    - run: sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0
      if: runner.os == 'Linux'
    - run: sudo sysctl kernel.apparmor_restrict_unprivileged_unconfined=0
      if: runner.os == 'Linux'
    - run: sudo sysctl kernel.unprivileged_userns_clone=1
      if: runner.os == 'Linux'
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Install nix
      uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b
      with:
        nix_path: "${{ matrix.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          system-features = gccarch-x86-64-v3 benchmark big-parallel kvm nixos-test uid-range
    - name: Setup cachix
      uses: cachix/cachix-action@v16
      # Don't replace <YOUR_CACHIX_NAME> here!
      if: ${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}
      with:
        name: ${{ matrix.cachixName }}
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Determine system architecture
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
            SYSTEM="aarch64-darwin"
          else
            SYSTEM="x86_64-darwin"
          fi
        elif [[ "${{ runner.arch }}" == "ARM64" ]]; then
          SYSTEM="aarch64-linux"
        else
          SYSTEM="x86_64-linux"
        fi
        echo "SYSTEM=$SYSTEM" >> $GITHUB_ENV
        echo "Building for system: $SYSTEM"
    # https://github.com/nix-community/nixos-apple-silicon/blob/7aad69158fc1b5bbbddac19040b6aae14daaa35c/.github/workflows/cache.yml#L45C56-L50C24
    # add timeout less than github hard timeout so there is time to upload cache.
    - name: Build nix packages
      if: runner.os == 'Linux'
      run: |
        timeout --foreground 5h nix run nixpkgs#nix-fast-build -- --max-jobs 1 --option cores 1 \
          --no-nom \
          -f .#packages.${{ env.SYSTEM }}.cached
    - name: Build nix packages
      if: runner.os != 'Linux'
      run: |
        nix run nixpkgs#nix-fast-build -- --max-jobs 1 \
          --no-nom \
          -f .#packages.${{ env.SYSTEM }}.cached
